Podcast_Streaming_Platform/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('podcast_user.urls')),
    path('basic/', include('basic_pages.urls')),
    path('blog/', include('podcast_blog.urls')),
    path('podcast/', include('podcast.urls')),
    path('api_user/', include('podcast_user.serializers_urls')),
    path('api_blog/', include('podcast_blog.serializers_urls')),
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

podcast/urls.py
from django.urls import path,re_path,include


urlpatterns = [

]

podcast_blog/models.py
from django.db import models
from datetime import date,datetime
from podcast_user.models import PodcastUser
from django.forms import Textarea
class Podcast_Blog(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=500, default="Post something!! (xc")
    time_of_blog = models.DateTimeField(default=datetime.now)
    blog_text = models.TextField(default="Must be something")
    blog_user = models.ForeignKey(PodcastUser,on_delete=models.CASCADE,blank=False, null=False)
    likes = models.ManyToManyField(PodcastUser, related_name='liked_blogs', blank=True)


    def __str__(self):
        return f"{self.id} , {self.name}, {self.blog_user} "

    def like(self, user):
        self.likes.add(user)

    def unlike(self, user):
        self.likes.remove(user)

class BlogComment(models.Model):
    id = models.AutoField(primary_key=True)
    blog = models.ForeignKey(Podcast_Blog, on_delete=models.CASCADE, related_name='comments')
    comment_text = models.TextField( help_text='Enter your comment here.')
    comment_user = models.ForeignKey(PodcastUser, on_delete=models.CASCADE, blank=False, null=False)
    time_of_comment = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f"{self.id}, {self.comment_text}, {self.comment_user}"

podcast_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin,AbstractUser
from django.core.validators import RegexValidator
from datetime import date
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class Country(models.Model):
    country_id = models.AutoField(primary_key=True)
    country_name = models.CharField(max_length=100)
    country_code = models.CharField(max_length=3)

    def __str__(self):
        return self.country_name

class PodcastUser(AbstractUser):
    user_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30,unique=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True, null=True, unique=True, default='+')
    date_of_birth = models.DateField(blank=True, null=True)
    date_of_join = models.DateField(blank=True, null=True,default=date.today)
    address = models.CharField(max_length=100,blank=True, null=True)
    image = models.ImageField(upload_to='user_images/', blank=True, null=True)
    city_name = models.CharField(max_length=30, blank=True, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True)
    postal_code = models.CharField(max_length=10,blank=True, null=True)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    email = models.EmailField(max_length=30,
                              validators=[RegexValidator(regex="^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.["r"a-zA-Z0-9-.]+$",
                                                         message='please enter the correct format')],unique=True)
    followers = models.ManyToManyField('self', symmetrical=False, related_name='following', blank=True )


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name','username','country']

    def create_superuser(self, email, password, **extra_fields):
        if self.filter(is_superuser=True).exists():
            raise ValueError('Superuser already exists')
        # set some default values for the superuser
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        # create the superuser with the provided email and password
        return self._create_user(email=email, password=password, **extra_fields)

    def __str__(self):
        return f"{self.username} ({self.user_id})"

class UserInfo(models.Model):
    user = models.ForeignKey(PodcastUser, on_delete=models.CASCADE,blank=False, null=False)
    bio = models.TextField()
    language = models.CharField(max_length=25, null=True,blank=True)
    education = models.CharField(max_length=100, null=True,blank=True)
    skills = models.CharField(max_length=25, null=True,blank=True)

    def __str__(self):
        return f"{self.user})"



@receiver(post_save, sender=PodcastUser)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

podcast_user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,UserChangeForm,PasswordChangeForm
from .models import PodcastUser,Country,UserInfo
from django import forms


class CustomUserCreationForm(UserCreationForm):
    phone_number = forms.CharField(max_length=17, required=False)
    country = forms.ModelChoiceField(queryset=Country.objects.all(), required=True)
    class Meta:
        model = PodcastUser
        fields = ('email','username', 'first_name', 'last_name', 'phone_number', 'password1', 'password2','country')

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label='Email')

class UserEditForm(UserChangeForm):
    password = None

    class Meta:
        model = PodcastUser
        fields = ('first_name', 'last_name', 'phone_number', 'address', 'city_name', 'postal_code', 'image')

class PasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label="Old Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label="New Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = PodcastUser
        fields = ('old_password', 'new_password1', 'new_password2')


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['bio', 'language', 'education', 'skills',]
        labels = {
            'bio': 'Biography',
            'language': 'Language',
            'education': 'Education',
            'skills': 'Skills',
        }
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 5}),
            'language': forms.TextInput(attrs={'placeholder': 'e.g. English, French'}),
            'education': forms.TextInput(attrs={'placeholder': 'e.g. Bachelor of Arts in History'}),
            'skills': forms.TextInput(attrs={'placeholder': 'e.g. Photoshop, Python'}),
        }

templates/pages/users/edit_user_info.html
{% extends 'navbar_footer_menu.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}

<div class="content-wrapper" xmlns="http://www.w3.org/1999/html">
    <!-- Main content -->
    <section class="content" style=" margin-left: 25%; margin-top:8%;">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">General</h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="card-body">
                {% if form %}
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.bio.id_for_label }}">Biography</label>
                        <textarea class="form-control" id="{{ form.bio.id_for_label }}" name="{{ form.bio.name }}"  value="{{ form.bio.value }}">{{ form.bio.value }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="{{ form.language.id_for_label }}">Language</label>
                        <input type="text" class="form-control" id="{{ form.language.id_for_label }}" name="{{ form.language.name }}" value="{{ form.language.value }}">
                    </div>
                    <div class="form-group">
                        <label for="{{ form.education.id_for_label }}">Education</label>
                        <input type="text" class="form-control" id="{{ form.education.id_for_label }}" name="{{ form.education.name }}" value="{{ form.education.value }}">
                    </div>
                    <div class="form-group">
                        <label for="{{ form.skills.id_for_label }}">Skills</label>
                        <input type="text" class="form-control" id="{{ form.skills.id_for_label }}" name="{{ form.skills.name }}" value="{{ form.skills.value }}">
                    </div>
                    <button type="submit" class="btn btn-success float-right">Save Changes</button>
                </form>
                {% endif %}

               </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>

{% endif %}
{% endblock %}

templates/pages/users/profile.html
{% extends 'navbar_footer_menu.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}

  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                    {% if user.image %}
                      <img class="profile-user-img img-fluid img-circle"
                           src="{{ user.image.url }}"
                           alt="User profile picture">
                    {% endif %}
                </div>

                <h3 class="profile-username text-center">{{ user.username}}</h3>

                <p class="text-muted text-center">{{ user.first_name }} {{ user.last_name}}</p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>Followers</b> <a class="float-right">{{ request.user.followers.count }}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Following</b> <a class="float-right">{{ following_count }}</a>
                  </li>

                </ul>

                <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">About Me</h3>
              </div>

              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fas fa-book mr-1"></i> Education</strong>

                <p class="text-muted">
                {{ user_info.education }}
                </p>

                <hr>

                <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                <p class="text-muted">{{ user.city_name }} , {{ user.country }} , {{user.postal_code}}</p>

                <hr>

                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>

                <p class="text-muted">
                  <span class="tag tag-danger">{{user_info.skills}}</span>

                </p>

                <hr>

                <strong><i class="far fa-file-alt mr-1"></i> Bio:</strong>

                <p class="text-muted">{{ user_info.bio }}</p>
              </div>
              <div class="card-header">
               <a href="{% url 'edit_user_info'%}"><i class="fa fa-cog" aria-hidden="true"> Edit user info</i></a>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Activity</a></li>
                  <li class="nav-item"><a class="nav-link" href="#Followers" data-toggle="tab">Followers </a></li>
                  <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Settings</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <div class="active tab-pane" id="activity">
                    <!-- Post -->
                    {% if blog_posts%}
                    {% for post in blog_posts %}
                    <div class="post">
                      <div class="user-block">
                        {% if user.image %}
                          <img class="img-circle img-bordered-sm" src="{{ user.image.url }}" alt="{{ user.username }}">
                        {% endif %}
                        <span class="username">
                          <a href="#">{{ post.name }}</a>
                          <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                        </span>
                        <span class="description">Shared publicly time: -<time>{{ post.time_of_blog|date:"H:i:s" }}</time></span>
                        <span class="description">Shared publicly date -<time>{{ post.time_of_blog|date:"d/m/Y" }}</time></span>
                      </div>
                      <!-- /.user-block -->
                      <p>{{ post.blog_text}} </p>
                      <p>
                          <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownComments" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                              <span class="float-right">
                                <i class="far fa-comments mr-1"></i> Comments {{ blog.comments.count }}
                              </span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownComments">
                              {% for comment in comments %}
                                <p style="margin-top: 10%;">{{ comment.comment_text|linebreaks }}</p>
                                  <small>by {{ comment.comment_user.username }} on {{ comment.time_of_comment }}</small>
                                {% empty %}
                                <p style="margin-top: 10%;">No comments yet.</p>
                              {% endfor %}
                            </div>
                          </div>
                      <span class="float-right">
                          <a href="#" class="link-black text-sm"><i class="far fa-thumbs-up mr-1"></i> Like {{ post.likes.count }}</a>
                        </span>
                      </p>
                    </div>
                    {% endfor %}
                    <!-- /.post -->
                    {% endif %}

                  </div>
                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="Followers">
                    <div class="container">
                        {% if request.user.is_authenticated %}
                            <p class="text-muted">Followers: {{ followers_count }}</p>
                            <ul>
                                {% for follower in request.user.followers.all %}
                                  {% if follower.image %}
                                    <li>{{ follower.username }} | <img src="{{ follower.image.url }}" class="profile-user-img img-fluid img-circle"></li>
                                  {% endif %}
                                {% empty %}
                                    <li>No followers yet.</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                  </div>
                  <!-- /.tab-pane -->

                  <div class="tab-pane" id="settings">
                    {% if user_form %}
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>
                          <label for="id_first_name">First name:</label>
                          <input type="text" name="first_name" class="form-control" value="{{ user.first_name }}"   id="id_first_name">
                        </p>

                        <p>
                          <label for="id_last_name">Last name:</label>
                          <input type="text" name="last_name" class="form-control" value="{{ user.last_name }}" id="id_last_name">
                        </p>

                        <p>
                          <label for="id_phone_number">Phone number:</label>
                          <input type="text" name="phone_number"  class="form-control" value="{{ user.phone_number }}" id="id_phone_number">
                        </p>

                        <p>
                          <label for="id_address">Address:</label>
                          <input type="text" name="address" class="form-control" value="{{ user.address }}"  id="id_address">
                        </p>

                        <p>
                          <label for="id_city_name">City name:</label>
                          <input type="text" name="city_name" class="form-control" value="{{ user.city_name }}" id="id_city_name">
                        </p>

                        <p>
                          <label for="id_postal_code">Postal code:</label>
                          <input type="text" name="postal_code" class="form-control"  value="{{ user.postal_code }}"  id="id_postal_code">
                        </p>

                        <p>
                          <label for="id_image">Image:</label>
                          {% if user.image %}
                          Currently: <a href="{{ user.image.url }}">{{ user.image.url }} </a>
                            <input type="checkbox"  name="image-clear" id="image-clear_id">
                            <label for="image-clear_id">Clear</label><br>
                           {% endif %}
                            Change:
                            <input type="file"  class="form-control" name="image" accept="image/*" id="id_image">
                        </p>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                      </form>

                    {% endif %}
                    {% if password_form %}
                      <h2>Change Password</h2>
                      <form method="post">
                        {% csrf_token %}
                        {{ password_form.as_p }}
                          <button type="submit" class="btn btn-danger">Change password </button>
                      </form>
                    {% endif %}

                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
{% endif %}
{% endblock %}

templates/pages/users/user_detail.html
{% extends 'navbar_footer_menu.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}

<div class="wrapper">
  <!-- Navbar -->
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                    {% if page_user.image %}
                        <img class="profile-user-img img-fluid img-circle"
                            src="{{ page_user.image.url }}"
                            alt="User profile picture">
                    {% else %}
                        <img class="profile-user-img img-fluid img-circle"
                                src=""
                                alt="User profile picture">
                    {% endif %}
                </div>

                <h3 class="profile-username text-center">{{ page_user.username }}</h3>

                <p class="text-muted text-center">{{ page_user.first_name }}{{ page_user.last_name }}</p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <strong><i class="fas fa fa-address-book mr-1"></i> Address: </strong>
                     <p class="text-muted">{{ page_user.address }} , {{ page_user.city }} , {{ page_user.country }} , {{ page_user.postal_code }}</p>
                  </li>
                  <li class="list-group-item">
                    <strong><i class="fas fa fa-phone mr-1"></i> Phone number:</strong>
                    <p class="text-muted">{{ page_user.phone_number }} </p>
                  </li>
                  <li class="list-group-item">
                    <strong><i class="fas fa fa-calendar mr-1"></i> Date of join:</strong>
                    <p class="text-muted">{{ page_user.date_of_join }}</p>
                  </li>
                  <li class="list-group-item">
                    <strong><i class="fas fa fa-clock mr-1"></i> Last time logged in:</strong>
                    <p class="text-muted">{{ page_user.last_login }}</p>
                  </li>
                  <li class="list-group-item">
                    <strong><i class="fas fa fa-birthday-cake mr-1"></i> Date of birth:</strong>
                    <p class="text-muted">{{ page_user.date_of_birth }}</p>
                  </li>
                </ul>
                    {% if request.page_user != user %}
                     {% if request.user in user.followers.all %}
                         <form action="{% url 'unfollow_user' user.user_id %}" method="POST">
                             {% csrf_token %}
                             <button type="submit" class="btn btn-danger btn-block"><b>Unfollow -</b></button>
                         </form>
                    {% else %}
                        <form action="{% url 'follow_user' user.user_id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-block"><b>Follow +</b></button>
                        </form>
                        {% endif %}
                    {% endif %}
<!--                <a href="#" class="btn btn-primary btn-block"><b>Follow +</b></a>-->
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">About Me</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fas fa-book mr-1"></i> Education</strong>
                <p class="text-muted">{{ page_user.user_info.education }}</p>
                <hr>
                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>
                <p class="text-muted">{{ page_user.user_info.skills }}</p>
                <hr>
                <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>
                <p class="text-muted">{{ user_info.bio }}</p>
                <p class="text-muted">Followers: {{ request.user.followers.count }}</p>
                <p class="text-muted">Following: {{ following_count }}</p>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Activity</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">

                  <div class="active tab-pane" id="activity">
                    <!-- Post -->
                    {% if blog_comments %}
                      {% for blog, comments in blog_comments %}
                    <div class="post">
                      <div class="user-block">
                         {% if page_user.image %}
                          <img class="img-circle img-bordered-sm" src="{{ page_user.image.url }}" alt="{{ page_user.username }}">
                        {% endif %}
                        <span class="username">
                          <a href="#">{{ blog.name }}</a>
                        </span>
                        <span class="description">Shared publicly time: -<time>{{ blog.time_of_blog|date:"H:i:s" }}</time></span>
                        <span class="description">Shared publicly date -<time>{{ blog.time_of_blog|date:"d/m/Y" }}</time></span>
                      </div>
                      <!-- /.user-block -->
                      <p>{{ blog.blog_text}}</p>
                        <p>
                            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                                <li class="nav-item">
                                    <div class="dropdown" >
                                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownComments" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                                        <span class="float-right">
                                              <i class="far fa-comments mr-1"></i> Comments {{ blog.comments.count }}
                                            </span>
                                      </button>
                                        {% if request.user.is_authenticated %}
                                            {% if request.user in blog.likes.all %}
                                                <a href="{% url 'unlike_blog' blog.id %}" class="link-black text-sm float-right"><i class="fas fa-thumbs-up mr-1"></i> Unlike {{ blog.likes.count }}</a>
                                            {% else %}
                                                <a href="{% url 'like_blog' blog.id %}" class="link-black text-sm float-right"><i class="far fa-thumbs-up mr-1"></i> Like {{ blog.likes.count }}</a>
                                            {% endif %}
                                        {% else %}
                                            <a href="{% url 'login' %}" class="link-black text-sm float-right"><i class="far fa-thumbs-up mr-1"></i> Like {{ blog.likes.count }}</a>
                                        {% endif %}
                                    <div class="dropdown-menu" aria-labelledby="dropdownComments">
                                        {% for comment in comments %}
                                             <p style="margin-top: 10%;">{{ comment.comment_text|linebreaks }}</p>
                                                 <small>by {{ comment.comment_user.username }} on {{ comment.time_of_comment }}</small>
                                          {% empty %}
                                            <p style="margin-top: 10%;">No comments yet.</p>
                                        {% endfor %}
                                    </div>
                                </div>
                                </li>
                            </ul>
                        </p>

                        <form method="post">
                            {% csrf_token %}
                                <div class="row">
                                    <textarea name="comment_text"class="form-control form-control-sm col-md-11" cols="1" rows="1" required="" id="id_comment_text" spellcheck="false"></textarea>
                                    <button type="submit" class="btn btn-danger">Send</button>
                                    <input type="hidden" name="blog_id" value="{{ blog.id }}">
                                </div>
                            </form>

                    </div>
                    <!-- /.post -->
                  {% endfor %}

                  {% endif %}
                  </div>
                </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
</div>
{% endif %}
{% endblock %}